name: build
env: { DOTNET_NOLOGO: true }
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
    types:
      - opened
      - ready_for_review
      - review_requested
jobs:
  pipeline:
    uses: panoukos41/NoSQLite/.github/workflows/_.yaml@main
    with:
      test: true